// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAZqJo0F7g9yvA5ziIMOxgSvLniaV5mkZo',
      appId: '1:21825747160:android:55ce82c3e4975a1b52ffad',
      messagingSenderId: '21825747160',
      projectId: 'aider-7a175',
      storageBucket: 'aider-7a175.firebasestorage.app',
    );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh3NGMby68uPCRqULbQfJLpFNf1ygqrHo',
    appId: '1:1072151404082:ios:deb83c894cb99572cd262b',
    messagingSenderId: '1072151404082',
    projectId: 'aider-bd0e4',
    storageBucket: 'aider-bd0e4.appspot.com',
    iosBundleId: 'com.aider.mobile',
  );
}
